#!/usr/bin/env bash
# Regenerate the pinned lockfiles from a clean virtualenv so they contain exactly the resolved tree.
set -euo pipefail
cd "$(dirname "$0")/.."
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
for kind in "" "-dev"; do
  python3 -m venv "$tmp/v$kind"
  "$tmp/v$kind/bin/pip" install -q -r "requirements$kind.in"
  { echo "# Generated by scripts/lock.sh from requirements$kind.in - do not edit by hand."; "$tmp/v$kind/bin/pip" freeze; } > "requirements$kind.txt"
done
echo "lockfiles updated"
